#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FLMotor,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     FRMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     BLMotor,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     BRMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     Intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"
#pragma DebuggerWindows("joystickSimple")

task main()
{
	while(1 == 1) //Start joystick loop
	{
		getJoystickSettings(joystick);     //Normal
		motor[FLMotor] = joystick.joy1_y1; //Controls
		motor[BLMotor] = joystick.joy1_y1; //For
		motor[FRMotor] = joystick.joy1_y2; //Standard
		motor[BRMotor] = joystick.joy1_y2; //Driving

		///////////////////////////////////////////////////////////////////

		if(joystick.joy1_TopHat == 0)// Start Forward Driving Controls
		{
			motor[FLMotor] = 64;
			motor[FRMotor] = 64;
			motor[BLMotor] = 64;
			motor[BRMotor] = 64;
		}
		else
		{
			motor[FLMotor] = 0;
			motor[FRMotor] = 0;
			motor[BLMotor] = 0;
			motor[BRMotor] = 0;
		}                            //End Forward Driving Controls

		///////////////////////////////////////////////////////////////////

		if(joystick.joy1_TopHat == 4)//Start Backwards Driving Controls
		{
			motor[FLMotor] = -64;
			motor[FRMotor] = -64;
			motor[BLMotor] = -64;
			motor[BRMotor] = -64;
		}
		else
		{
			motor[FLMotor] = 0;
			motor[FRMotor] = 0;
			motor[BLMotor] = 0;
			motor[BRMotor] = 0;
		}                            //End Backwards Driving Controls

		///////////////////////////////////////////////////////////////////

		if(joystick.joy1_TopHat == 2)//Start Turn Right Driving Controls
		{
			motor[FLMotor] = 64;
			motor[FRMotor] = -64;
			motor[BLMotor] = 64;
			motor[BRMotor] = -64;
		}
		else
		{
			motor[FLMotor] = 0;
			motor[FRMotor] = 0;
			motor[BLMotor] = 0;
			motor[BRMotor] = 0;
		}                            //End Turn Right Driving Controls

		///////////////////////////////////////////////////////////////////

		if(joystick.joy1_TopHat == 7)//Strat Turn Left Driving Controls
		{
			motor[FLMotor] = -64;
			motor[FRMotor] = 64;
			motor[BLMotor] = -64;
			motor[BRMotor] = 64;
		}
		else
		{
			motor[FLMotor] = 0;
			motor[FRMotor] = 0;
			motor[BLMotor] = 0;
			motor[BRMotor] = 0;
		}

		///////////////////////////////////////////////////////////////////

		if(joystick.joy2_TopHat == 0)//Start Intake Pull
		{
			motor[Intake] = 64;
		}
		else
		{
			motor[Intake] = 0;
		}                            //End Intake Pull

		///////////////////////////////////////////////////////////////////

		if(joystick.joy2_TopHat == 4)//Start Intake Push
		{
			motor[Intake] = -64;
		}
		else
		{
			motor[Intake] = 0;
		}                            //End Intake Push

		///////////////////////////////////////////////////////////////////

	}                              //End Joystick Loop
}
