#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     IRSeeker2,           sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int x = 0;

task main()
{
  while(1 == 1)
  {
    if(SensorValue[IRSeeker2] == 1)
    {
      x = 1;
    }
    else if(SensorValue[IRSeeker2] == 2)
    {
      x = 2;
    }
    else if(SensorValue[IRSeeker2] == 3)
    {
    	x = 3;
    }
    else if(SensorValue[IRSeeker2] == 4)
    {
      x = 4;
    }
    else if(SensorValue[IRSeeker2] == 5)
    {
      x = 5;
    }
    else if(SensorValue[IRSeeker2] == 5)
    {
      x = 6;
    }
    else if(SensorValue[IRSeeker2] == 7)
    {
      x = 7;
    }
    else if(SensorValue[IRSeeker2] == 8)
    {
      x = 8;
    }
    else if(SensorValue[IRSeeker2] == 9)
    {
      x = 9;
    }
    else
    {
    	x = 0;
    }
  }
}
