#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker2,      sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     intake,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     backLeft,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    release,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Marioooo.c"
#include "DarudeSandstorm.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "manhandle" the Bluetooth messages.

int x = 0;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//	 5. Fix the Wifi at DHS
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

  waitForStart();   // wait for start of tele-op phase

  while(true)
  {

  	if(joystick.joy1_TopHat == 0)
  	{
  		motor[backLeft] = 128;
  		motor[backRight] = 128;
  	}
  	else if(joystick.joy1_TopHat == 2)
  	{
  		motor[backLeft] = 128;
  		motor[backRight] = -128;
  	}
  	else if(joystick.joy1_TopHat == 4)
  	{
  		motor[backLeft] = -128;
  		motor[backRight] = -128;
  	}
  	else if(joystick.joy1_TopHat == 6)
  	{
  		motor[backLeft] = -128;
  		motor[backRight] = 128;
  	}
  	else
  	{
  		motor[backLeft] = joystick.joy1_y1;
  	  motor[backRight] = joystick.joy1_y2;
  	}

  	if(joy1Btn(1) == 1)
  	{
  		servo[release] = 255;
  	}
  	else if(joy1Btn(2) == 1)
  	{
  		servo[release] = 132;
  	}

  	if(joy1Btn(6) == 1)
  	{
  		motor[lift] = 128;
  	}
  	else if(joy1Btn(8) == 1)
  	{
  		motor[lift] = -128;
  	}
  	else
  	{
  		motor[lift] = 0;
  	}

  	if(joy1Btn(5) == 1)
  	{
  		motor[intake] = 128;
  	}
  	else if(joy1Btn(7) == 1)
  	{
  		motor[intake] = -128;
  	}
  	else
  	{
  		motor[intake] = 0;
  	}

  	if(SensorValue[IRSeeker2] == 1)
    {
      x = 1;
    }
    else if(SensorValue[IRSeeker2] == 2)
    {
      x = 2;
    }
    else if(SensorValue[IRSeeker2] == 3)
    {
    	x = 3;
    }
    else if(SensorValue[IRSeeker2] == 4)
    {
      x = 4;
    }
    else if(SensorValue[IRSeeker2] == 5)
    {
      x = 5;
    }
    else if(SensorValue[IRSeeker2] == 5)
    {
      x = 6;
    }
    else if(SensorValue[IRSeeker2] == 7)
    {
      x = 7;
    }
    else if(SensorValue[IRSeeker2] == 8)
    {
      x = 8;
    }
    else if(SensorValue[IRSeeker2] == 9)
    {
      x = 9;
    }
    else
    {
    	x = 0;
    }

    if(joy1Btn(10) == 1)
    {
    	//Mario();
      DarudeSandstorm();
    	wait1Msec(1);
    }

  }
}
